name: Release
on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      checkout-ref:
        description: "The branch, tag or commit to checkout."
        type: string
        required: false
jobs:
  checks:
    name: Checks
    uses: ./.github/workflows/checks.yml
  release:
    name: Release
    needs: [ checks ]
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ inputs.checkout-ref }}
          fetch-depth: 0
      - name: Configure semantic-release
        run: |
          cat >.releaserc.yaml <<EOL
          preset: conventionalcommits
          plugins:
            - "@semantic-release/commit-analyzer"
            - "@semantic-release/release-notes-generator"
            - "@semantic-release/github"
          EOL
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: >
          npx
          --package semantic-release@24
          --package conventional-changelog-conventionalcommits@9
          --
          semantic-release
